name: bureau1440
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    networks:
      - general-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities:
                - gpu
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=4
    networks:
      - general-net

  app:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - general-net

networks:
  general-net:
    driver: bridge